# Site settings
title: Campaign Finance Ideas
email: ken@polyoptik.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/btc-brutal/" # the subpath of your site, e.g. /blog/
url: "http://kwhaler.github.io" # the base hostname & protocol for your site
twitter_username: kwhaler
github_username:  kwhaler

# Build settings
markdown: kramdown
